<div class="main-container col1-layout">
            <div class="main">
                                <div class="col-main">
                                        <div class="std"><div class="header-recr"><img src="https://popeyes.vn/media/wysiwyg/popeyes/career_header_1.png"></div>
<div class="container content-recr">
<h3 style="text-align: left;">HÃY VỀ ĐỘI CỦA POPEYES!</h3>
<div class="caption" style="text-align: left;"></div>
<div class="caption">
<p style="text-align: left;"><span style="font-size: large;"><strong>1. Vị trí tuyển dụng:</strong></span><br>- Nhân viên phục vụ:<br>Part-time: 4 - 6 tiếng/ngày (ca xoay)<br>Full-time: 8 tiếng/ngày (ca xoay)<br>- Quản lý/Trợ lý/Giám sát ca nhà hàng.</p>
<p style="text-align: left;"><span style="font-size: large;"><strong>2. Địa điểm làm việc:</strong></span>&nbsp;các nhà hàng trong hệ thống chuỗi nhà hàng Popeyes - khu vực Hồ Chí Minh và Hà Nội</p>
<p style="text-align: left;"><span style="font-size: large;"><strong>3. Yêu cầu chung:</strong></span></p>
<p style="text-align: left;">- Độ tuổi: từ đủ 18 tuổi đến 45 tuổi ( đã tốt nghiệp THCS)<br>- Yêu thích làm việc trong lĩnh vực nhà hàng, yêu thích chế biến món ăn, sẵn sàng học hỏi và luân chuyển bộ phận làm việc để phát triển kỹ năng.<br>- Nhanh nhẹn, nhiệt tình, đam mê công việc, sức khỏe tốt.</p>
<p style="text-align: left;"><em>1. Nhân viên phục vụ:</em>&nbsp;<br>Trình độ: tốt nghiệp PTTH, từ đủ 18 tuổi trở lên.<br>Ưu tiên các bạn nam, có thể đi giao hàng và làm được đến 11h30 tối.<br>Khả năng giao tiếp Anh văn cơ bản.<br><em>2. Quản lý/Trợ lý/Giám sát ca nhà hàng:&nbsp;</em><br>Trình độ học vấn tối thiểu: tốt nghiệp Cao đẳng / Đại học.<br>Kinh nghiệm: ít nhất có 3-5 năm kinh nghiệm trong ngành quản lý (ưu tiên các ứng viên đã từng làm việc trong ngành F&amp;B, có kiến thức làm việc trong môi trường nhà hàng / dịch vụ…)<br>Kỹ năng quản lý tốt, học hỏi nhanh.<br>Khả năng giao tiếp anh văn cơ bản.</p>
<p style="text-align: left;"><span style="font-size: large;"><strong>5. Chế độ:&nbsp;</strong></span><br><span>- Ca làm việc linh động theo lịch học (part time: 4-6h/ngày, full time: 8h/ngày)</span><br><span>- Làm việc trong môi trường trẻ trung, năng động.</span><br><span>- Cơ hội thăng tiến rõ ràng: trưởng nhóm/giám sát/trợ lý/quản lý nhà hàng.</span><br><span>- Được đào tạo, tập huấn thường xuyên về sản phẩm, nghiệp vụ &amp; các kỹ năng (bán hàng, giao tiếp khách hàng…)</span><br><span>- Trợ cấp giao hàng.</span><br><span>- Thưởng doanh số tổ chức tiệc.</span><br><span class="_5mfr"><span class="_6qdm"></span></span><span>- Thưởng các dịp lễ, Tết.</span><br><span class="_5mfr"><span class="_6qdm">❤️</span></span><span style="background-color: #ffff00;"><strong>MỨC LƯƠNG: 21.500đ-24.000đ/Giờ (part-time) , 4.420.000đ-4.730.000đ + phụ cấp 520.000đ (FULL-Time)</strong></span></p>
<p style="text-align: left;"><span style="font-size: large;"><strong>6. Phương thức ứng tuyển:</strong></span></p>
<p style="text-align: left;"><em>1. Nhân viên phục vụ:</em></p>

<p style="text-align: left;"><span style="text-decoration: underline;">❤️Khu vực Hà Nội❤️</span><br><span class="_5mfr"><span class="_6qdm">➡️</span></span><span>&nbsp;Liên hệ Ms. Trang 024.7300.0535 ext 40000 hoặc 0985.359.780</span><br><span class="_5mfr"><span class="_6qdm">➡️</span></span><span>&nbsp;Nộp hồ sơ cho nhà tớ qua đường link:<span style="color: #ff6600;"><strong><a href="https://forms.gle/BvLf2kiTjPX4i1fB8?fbclid=IwAR0BoNhgXc5QjILf9vjAvure1tlRgILlyG3t8Tx_yppDuDKGjQxZwmTq8C0" rel="nofollow noopener" target="_blank" data-lynx-mode="hover" data-lynx-uri="https://l.facebook.com/l.php?u=https%3A%2F%2Fforms.gle%2FBvLf2kiTjPX4i1fB8%3Ffbclid%3DIwAR0BoNhgXc5QjILf9vjAvure1tlRgILlyG3t8Tx_yppDuDKGjQxZwmTq8C0&amp;h=AT1V-t9c6-tAVINfFcolxIsMO51m_DQ0ezuubvIzNqSLN0IjVKEwIVA3NTfA8I2lAOhNkjUiK5WaF9iZGPO_CYkpRkDE4S7eVnuEczcPqhKyClkcCDafq8l1dl1H_M5ovgZR"><span style="color: #ff6600;">https://forms.gle/BvLf2kiTjPX4i1fB8</span></a></strong></span></span><br><span class="_5mfr"><span class="_6qdm">➡️</span></span><span>&nbsp;Nộp trực tiếp đến cửa hàng bạn mong muốn làm việc:&nbsp;</span><span style="color: #ff6600;"><strong><a href="https://popeyes.vn/store.html/?fbclid=IwAR2AOpPbyRU8r_NnbNdMTSj6bWcBzOLrNjDTFvQvn2grmpLClOhJi02srC4" rel="nofollow noopener" target="_blank" data-lynx-mode="asynclazy" data-lynx-uri="https://l.facebook.com/l.php?u=https%3A%2F%2Fpopeyes.vn%2Fstore.html%2F%3Ffbclid%3DIwAR2AOpPbyRU8r_NnbNdMTSj6bWcBzOLrNjDTFvQvn2grmpLClOhJi02srC4&amp;h=AT0Qnkn2NOd6cwZX8jepOplQ9PGmzT655ZL70y7qP07-AFmQ6D-5BKXIbNiWe9DAxyhsIjWot8iR-0TWZd1mtX2cb3eBdYIfyUIIURf4JsSxtD8rcRIIavcoKAqdrryqyHkKlXYW"><span style="color: #ff6600;">https://popeyes.vn/<span class="word_break"></span>store.html/</span></a></strong></span><br><span class="_5mfr"><span class="_6qdm">➡️</span></span><span>&nbsp;Nộp hồ sơ tại Công Ty: VP nhân sự tầng 2, tòa nhà Corner Stone 16 Phan Chu Trinh, P. Phan Chu Trinh, Q. Hoàn Kiếm, Hà Nội</span><br><br></p>
<p style="text-align: left;"><em>2. Trợ lý/ Giám sát nhà hàng:</em><br><span class="_5mfr"><span class="_6qdm">➡️</span></span>&nbsp;Nộp CV qua mail : Ms. Mai&nbsp;<a href="maikhuong18021999@gmail.com">maikhuong18021999@gmail.com</a></p>
<p style="text-align: left;"></p>
<p style="text-align: left;">** Lưu ý: NỘP HỒ SƠ &amp; PHỎNG VẤN MIỄN PHÍ!</p>
</div>
</div></div>                </div>
            </div>
        </div>